// Las cuentas ya no se siembran: las crea el usuario (Patrimonio hoy, onboarding en PR F).
export const SEED_CATEGORIES = [
  ["cat-casa", "Casa", "", "expense", "need", 10],
  ["cat-casa-alquiler", "Alquiler/Hipoteca", "cat-casa", "expense", "need", 11],
  ["cat-casa-luz", "Luz", "cat-casa", "expense", "need", 12],
  ["cat-casa-agua", "Agua", "cat-casa", "expense", "need", 13],
  ["cat-casa-gas", "Gas", "cat-casa", "expense", "need", 14],
  ["cat-casa-internet", "Internet", "cat-casa", "expense", "need", 15],
  ["cat-casa-hogar", "Hogar", "cat-casa", "expense", "need", 16],
  ["cat-alimentacion", "Alimentación", "", "expense", "need", 20],
  ["cat-alimentacion-supermercado", "Supermercado", "cat-alimentacion", "expense", "need", 21],
  ["cat-alimentacion-domicilio", "Comida a domicilio", "cat-alimentacion", "expense", "want", 22],
  ["cat-restauracion", "Restauración", "", "expense", "want", 30],
  ["cat-restauracion-restaurantes", "Restaurantes", "cat-restauracion", "expense", "want", 31],
  ["cat-restauracion-bares", "Bares y cafés", "cat-restauracion", "expense", "want", 32],
  ["cat-transporte", "Transporte", "", "expense", "need", 40],
  ["cat-transporte-gasolina", "Gasolina", "cat-transporte", "expense", "need", 41],
  ["cat-transporte-publico", "Transporte público", "cat-transporte", "expense", "need", 42],
  ["cat-transporte-parking", "Parking/peajes", "cat-transporte", "expense", "want", 43],
  ["cat-transporte-taxi", "Taxi/VTC", "cat-transporte", "expense", "want", 44],
  ["cat-coche", "Coche", "", "expense", "need", 50],
  ["cat-coche-prestamo", "Préstamo", "cat-coche", "expense", "need", 51],
  ["cat-coche-seguro", "Seguro", "cat-coche", "expense", "need", 52],
  ["cat-coche-mantenimiento", "Mantenimiento/ITV", "cat-coche", "expense", "need", 53],
  ["cat-salud", "Salud", "", "expense", "need", 60],
  ["cat-salud-farmacia", "Farmacia", "cat-salud", "expense", "need", 61],
  ["cat-salud-medico", "Médico", "cat-salud", "expense", "need", 62],
  ["cat-salud-gimnasio", "Gimnasio", "cat-salud", "expense", "want", 63],
  ["cat-suscripciones", "Suscripciones", "", "expense", "want", 70],
  ["cat-suscripciones-streaming", "Streaming", "cat-suscripciones", "expense", "want", 71],
  ["cat-suscripciones-software", "Software", "cat-suscripciones", "expense", "want", 72],
  ["cat-suscripciones-otras-subs", "Otras", "cat-suscripciones", "expense", "want", 73],
  ["cat-ocio", "Ocio", "", "expense", "want", 80],
  ["cat-ocio-planes", "Planes y eventos", "cat-ocio", "expense", "want", 81],
  ["cat-ocio-viajes", "Viajes", "cat-ocio", "expense", "want", 82],
  ["cat-ocio-hobbies", "Hobbies", "cat-ocio", "expense", "want", 83],
  ["cat-ropa", "Ropa y cuidado personal", "", "expense", "want", 90],
  ["cat-regalos", "Regalos y donaciones", "", "expense", "want", 100],
  ["cat-impuestos", "Impuestos y tasas", "", "expense", "need", 110],
  ["cat-otros", "Otros gastos", "", "expense", "want", 120],
  ["cat-nomina", "Ingresos", "", "income", "", 910],
  ["cat-puntuales", "Ingresos puntuales", "", "income", "", 920],
  ["cat-intereses", "Intereses de ahorro", "", "income", "", 930],
];
export function seedStatements(now) {
  return [
    { sql: "INSERT INTO categories (id,name,parent_id,flow,need_type,display_order,is_archived,created_at,updated_at,deleted) VALUES (?,?,?,?,?,?,0,'" + now + "','" + now + "',0)", rows: SEED_CATEGORIES },
  ];
}
